### ISSUE TITLE
[TRACKING] `builder-init` scaffolding on brand new projects 

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/builder#7]
**Preliminary Matter**: This will need two PRs:

* `builder`: The init support
* `builder-react-component`: Has completely untested templates in WIP branch https://github.com/FormidableLabs/builder-react-component/compare/feature-init Please take this branch over.

Tasks

* [ ] Support `builder-init` via CLI input
* [ ] Support `builder-init` without CLI input somehow (needed for travis).
* [ ] Add to Travis
* [ ] Write up all documentation for soup-to-nuts init'ing for `builder-react-component`

Some helpful guidlines

* Use lodash templates
* Use `async.js` control flows for async stuff.
* All file / OS methods should be async. (Synchronous `require()`'s are ok)

### Basic Workflow

A user can bootstrap a project off an archetype. Use case:

```sh
$ mkdir foo && cd foo
$ git init .
$ npm install -g builder-init
$ builder-init builder-react-component
```

The first thing `builder init ARCHETYPE` does is internally

```sh
$ npm install builder-react-component
```

And from there, the ARCHETYPE's templates, etc. can be read.

After that, the user is asked about ARCHETYPE's context variables needed to
inflate the templates:

* [ ] OPEN QUESTION: How do we create the prompts and organize the template
  variables? I dislike a meta config file, but we may need it.

During the init, the user should be prompted for the following questions
for `builder-react-component`.

* `OrgName`: (1) change to `orgName`, (2) ask ;)
* `projectNpmDescription`: Description for `package.json:description` and README.
* `orgGitHubName`
* `projectNpmName`

This other information should be automatically inferred:

* `dateYear`: Current year.
* `componentClassName`: Derived from Pascal-casing `projectNpmName`
* `projectComponentPath`: Uses value in `projectNpmName` since right now they can't be skewed.

Things that aren't handled currently:

* The following file paths need to be created like:
  * `templates/src/components/<%= projectComponentPath %>.jsx (this is in the branch)
  * `templates/test/client/spec/components/<%= projectComponentPath %>.spec.jsx (this is currently missing in the branch)

Once all of those questions are answered, `builder init` then:

1. Checks that no files whatsoever conflict with **anything** that is in the templates to be written. (This includes `package.json` which we'll template in from scratch).
2. If any collisions, error out without mutating anything.
3. If no collisions, populate out all of the files.
4. Runs `npm install` with the newly-templated `package.json`
5. Runs `builder run check` to verify everything works.

Open questions at this point:

* [ ] OPEN QUESTION: Run `builder run build`? This creates `dist/` files which shouldn't be in initial git commit probably.
* [ ] OPEN QUESTION: How do we have an archetype define "run `builder run check` when `builder init` runs"? Again, would like to avoid an `ARCHETYPE/init-meta.js` meta config file if possible, but...

### Travis

As part of the testing of the scaffolding, we should test in Travis via something like the following `script` commands in the `builder-react-component/.travis.yml` (don't use the templated one).

A psuedo code version of the `.travis.yml` additions would be:

```yml
script:
  - npm --version
  - npm run builder:check
  # Create test directory and change into it.
  - mkdir SCAFFOLD_TEST && cd SCAFFOLD_TEST
  - npm install builder
  # Need support for relative path to archetype probably vs. from `npm`
  # Also need "no CLI input" version of `init`
  - node_modules/.bin/builder init ../
  - node_modules/.bin/builder run check-ci
```

**Comment by boygirl** [comment]
victory specific requests:
- ecology docs boilerplate
- `contributing.md`

**Comment by boygirl** [comment]
It really seems like we could kill the generators / boilerplate with archetypes

**Comment by chaseadamsio** [comment]
So there are essentially 2 different tasks here to get the initialization up and running:

- `builder init` should know based on something (`init.json`?) from the archetype what should be scaffolded on initialization
- There needs to be a `templates` set in the https://github.com/FormidableLabs/builder-react-component

There is a chicken or the egg scenario in that a `.builderrc` is necessary to know what archetype to use.

**Comment by ryan-roemer** [comment]
So there are two ways of looking at this:

* Retrofitting an existing project.
* Starting from scratch

In the start from scratch scenario, you would do this:

```
$ npm init
$ npm install --save builder builder-react-component
$ npm install --save-dev builder-react-component-dev
$ builder init
```

And builder would:

1. Mutate _only_ `package.json`
2. Nuke everything / overwrite everywhere else with boilerplate.

This is a much easier world to support.

If we're going for the "be nice in an existing project and retrofit", that is going to require a **lot** more work to do right. I favor number 1 -- only init.

Thoughts?

**Comment by chaseadamsio** [comment]
I think that works. So in the case of creating an app boilerplate, would you want to generate a `src/index.js`, `src/components/<name>.jsx`, `test/spec/components/<name>.spec.jsx` with a name that `builder init` prompts for?

**Comment by ryan-roemer** [comment]
Yes, and _everything else_ besides the pre-existing `package.json` that we'll mutate. Including:

* `.gitignore`
* `.npmignore`
* `.travis.yml`
* etc.

**Comment by chaseadamsio** [comment]
I  can get behind that. So would the idea for generating the `.builderrc` be that it looks through your package.json and determines what your archetype is?

**Comment by ryan-roemer** [comment]
@chaseadamsio -- It's even easier: because you start with an empty package, by definition, only _one_ archetype can `init`. At least for getting out of the gate, I think that makes sense as a simplifying constraint.

**Comment by chaseadamsio** [comment]
So here's how I see the work that needs to be done:

- [ ] `bin/builder.js` is going to need to be modified so that the `init` task can generate the `.builderrc` before `Config` is instantiated
- [ ] `lib/task` will have one more command added to the `ACTIONS` for `init`
- [ ] `init` will look for templates in the archetype and generate the files into the project root from the templates
- [ ] Ideally the user would be prompted for the name they want to give their first component and if they respond with one, it generates the correct files. If they leave it blank, it just scaffolds the directories without the component files but adds everything else.

@ryan-roemer lmk if you'd like for me to take this task on

**Comment by chaseadamsio** [comment]
# User Narrative

I'm creating a new project that will use `builder` and a `builder` archetype. By the time I've gotten to the `builder init` stage, I should have already:

- run `npm init` in my project root (which created my `package.json`)
- install `builder` globally and locally 
- install the archetype and archetype-dev dependencies into my project root

When I run `builder init`, I expect that `builder` will do the following for me:

- Create a `.builderrc` or `builder` in `package.json` of my archetype (what if this was _actually_ a part of installing the archetype as a `postinstall` script, since you absolutely need it anyways?)
- Create any file scaffolding that has been determined by the archetype maintainer should be a part of my project
- Update `package.json` with the `npm:*` scripts 

After I'm done doing that, I should be able to, without any extra work, spin up a server to see what was scaffolded.

**Comment by chaseadamsio** [comment]
`.builderrc` is copied into the project root by the `builder` archetype on `postinstall`

## User Narrative: Consumer

I want to create a new project based on a builder archetype.

I've created a new project(directory) called "foo" and I want to scaffold it out.

First, I run `npm init` to make sure I have a `package.json` and run:

```
$ npm install builder <builder-archetype> <builder-archetype>-dev
```

if the `.builderrc` is generated into the project during `postinstall`, we now bypass builder needing to infer the archetype.

(I run `builder init` and I'm prompted for anything that can't be inferred from the `package.json` (org, repository name, etc))

Once `builder init` has all the info it needs, it does the following:

- Scaffolding for initial files is generated. v1 would always scaffold whatever is in the `/templates` directory, but future iterations could detect if a value was given and if not, skip the files that need it
- Updated the `package.json` with the `npm:*` scripts and _backup_ any scripts that may already exist (unless it's the `test` script and it's the default `npm init` test script)

After I'm done doing that, I should be able to, without any extra work, spin up a server to view the project in the browser

## What Lives Where

### Builder

- A script for `init` that does the following:
    - reads the `manifest` from a project and uses the manifest to prompt
    - runs the templates through handlebars with a manifest object and creates the files in the project root
    - adds the `npm:*` tasks to the root project and moves any of the scripts it replaces to `<script>:bak` (with exception of the `test` script that's generated by `npm` that says "no tests", we should just blow that away)

### The Archetype

- A `.builderrc` 
- A `scripts:postinstall` that copies `.builderrc` to the project root.
- A `/templates` directory with everything that should be copied into the project root.
- A `manifest` of some sort of what handlebars variables you expect and how they should be requested.

**Comment by exogen** [comment]
Still catching up, but I think it's overreaching for a `postinstall` to write files outside of its own directory. (As a general rule, the mere act of installing a package causing non-local filesystem modifications seems very presumptuous.)

Plus *I think* with npm@3's `node_modules` flattening behavior, it might be possible that installing a package that *uses*  builder would result in `builder-react-component` ending up in your package's root `node_modules` and not `subpackage-that-uses-builder/node_modules`, so it'd do the wrong thing.

Any alternatives that are nearly as convenient?

**Comment by chaseadamsio** [comment]
yep, we're going to have `builder init` do the work for us.

**Comment by exogen** [comment]
Ah, gotcha – must have been discussed already :+1:

**Comment by exogen** [comment]
Think I'm caught up, but I think there was a Slack discussion that I couldn't attend unfortunately, so you've probably already discussed this:

I would heavily prefer to lean toward having `npm init` do its thing and having `builder init` patch the resulting `package.json`. (If there's no existing `package.json`, we could just have `builder init` run `npm init` first.) I don't like the idea of (1) having to remember *not* to run `npm init` – I may not have even decided whether I'm going to use Builder at that point, and (2) having to wipe my `package.json` if I decide to adopt Builder later.

**Comment by chaseadamsio** [comment]
So did we decide to put the responsibility of `npm init` on the user before running `builder init [archetype]`?

**Comment by boygirl** [comment]
I'm happy either way. If we didn't require the user to run `npm init` first, would the syntax be something like
`builder init <project-name> <archetype-package-name>` ?

**Comment by chaseadamsio** [comment]
Since `package.json` is "copied" from the templates, you wouldn't technically need to do any `npm init`ing...here's an example of where it is now:

![builder-init](https://cloud.githubusercontent.com/assets/1024544/11384373/fc35a978-92c3-11e5-8e4a-02bd28b5e63b.gif)

The `package.json`'s lodash template is interpolated with the value passed into the prompt.

**Comment by boygirl** [comment]
oh, that's really nice. I prefer one step with prompts over `npm init` followed by `builder init`.

**Comment by chaseadamsio** [comment]
:+1: that makes me happy since I did the work to make it happen! I just pushed the initial commit for the code...I still need to do my personal sanity check on it before submitting it, but if you're interested, this is the branch: https://github.com/FormidableLabs/builder/compare/feature-addInitTask?expand=1

**Comment by chaseadamsio** [comment]
@ryan-roemer can you layout the scenario where we'd need:

> I dislike a meta config file, but we may need it.

**Comment by ryan-roemer** [comment]
@chaseadamsio -- Search on "meta" above. Here are two scenarios:

* **Prompt Defaults**: How can we have intelligent default prompts for both the interactive CLI and the "automatic for CI" scaffolding?
* **Checks**: We want to run "a check" after the scaffold is installed. For `builder-react-component` this is `builder run check`. How do we _know_ which command to run as the "check" after scaffolding?

**Comment by ryan-roemer** [comment]
@chaseadamsio -- Looked at your WIP branch. Oh yeah this stuff: https://github.com/FormidableLabs/builder/compare/feature-addInitTask?expand=1#diff-3e18cf2294c02344381d224486ff0d2dR71 that's **not** `builder` appropriate, that's `builder-react-component` appropriate. 

This:

```js
[{
    name: "OrgName",
    description: "Organization Name:"
  }, {
    name: "projectNpmDescription",
    description: "Project Description:"
  }, {
    name: "orgGitHubName",
    description: "Organization Github Name:"
  }, {
    name: "projectNpmName",
    description: "Project npm Name:"
  }]
```

Needs to be part of the **archetype**.

**Comment by chaseadamsio** [comment]
Yeah, I was actually going to ask about that. Once the builder archetype has been installed, there'd be a `json` file with this that'd get read and the values would get passed the way they do now.

For example, in `builder-react-component` there would be a `prompts.json` that has:

```
[{
    name: "OrgName",
    description: "Organization Name:"
  }, {
    name: "projectNpmDescription",
    description: "Project Description:"
  }, {
    name: "orgGitHubName",
    description: "Organization Github Name:"
  }, {
    name: "projectNpmName",
    description: "Project npm Name:"
  }]
```
So there'd be flexibility for each archetype to define its own variables.

The other thing that could give us some flexibility is having `template_` in file names where the archetype maintainer wants to replace the name with the one of the variables.

Thoughts?

**Comment by boygirl** [comment]
@chaseadamsio being able to replace file names is definitely desirable

**Comment by boygirl** [comment]
@chaseadamsio how's this coming? I'm super excited to start using it for victory

**Comment by chaseadamsio** [comment]
I'm dedicating the rest of the afternoon to hopefully get @ryan-roemer's insights on the prompts being moved into the archetype and attempting to get the Travis bit to work. Hoping to have it done by EOW...sorry it's taken so long!

**Comment by ryan-roemer** [comment]
Shipped!
