### ISSUE TITLE
Feature / Research: `builder check-deps` to verify ROOT deps match ARCHETYPE deps

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/builder#78]
For duplicate dependencies in `ROOT/package.json` and `ARCHETYPE/package.json` and `ARCHETYPE/dev/package.json` we would like to know / error if there is a mismatch in dependencies.

**TASK**

* [ ] Research if this can easily be done with just a scripted task in the archetype `package.json:scripts`
* [ ] If not, look into a `builder check-deps` action and formulate an implementation plan

**`check-deps`**

If we're doing this, rough strawman tasks:

* [ ] Verify dependencies from `ROOT/package.json:dependencies` vs. `ARCHETYPE/package.json:dependencies`
    * [ ] Disable with `--no-prod` flag, otherwise check.
* [ ] Verify dependencies from `ROOT/package.json:devDependencies` vs. `ARCHETYPE/dev/package.json:dependencies`
    * [ ] Disable with `--no-dev` flag, otherwise check.
* [ ] Display mismatches and exit non-zero if mismatches.
