### ISSUE TITLE
[TRACKING] NODE_PATH collisions in builder itself vs other deps

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/builder#99]
From the trenches:

* [ ] Lodash somehow became 4.5.x despite 3.10.x being in this package.json. This is like due to NODE_PATH munging and the fact that `builder/node_modules` is **not** currently part of the NODE_PATH resolution.
* [x] Many methods like `.map()` lost `this` as a last argument option.

Task

* [ ] Add `builder/node_modules` to NODE_PATH and figure out how to deal with potential conflicts with other `lodash` etc. conflicts... (This may be hard -- test by dropping ROOT/lodash of different versions).
* [ ] Maybe update to lodash 4.5

Error:

```
[builder:config:environment] {"cwd":"/PATH/TO","dir":"/PATH/TO/node_modules/builder/lib"}
/PATH/TO/node_modules/builder/lib/config.js:143
      return _.extend({ name: name }, this._loadArchetypePkg(name));
                                          ^

TypeError: Cannot read property '_loadArchetypePkg' of undefined
    at /PATH/TO/node_modules/builder/lib/config.js:143:43
    at arrayMap (/PATH/TO/node_modules/lodash/lodash.js:604:23)
    at Function.map (/PATH/TO/node_modules/lodash/lodash.js:7974:14)
    at interceptor (/PATH/TO/node_modules/lodash/lodash.js:14821:35)
    at thru (/PATH/TO/node_modules/lodash/lodash.js:7262:14)
    at /PATH/TO/node_modules/lodash/lodash.js:3736:28
    at arrayReduce (/PATH/TO/node_modules/lodash/lodash.js:647:21)
    at baseWrapperValue (/PATH/TO/node_modules/lodash/lodash.js:3735:14)
    at LazyWrapper.lazyValue [as value] (/PATH/TO/node_modules/lodash/lodash.js:1682:16)
    at baseWrapperValue (/PATH/TO/node_modules/lodash/lodash.js:3733:25)
```

**Comment by ryan-roemer** [comment]
Ack! Github commit messages gone awry! This is only bandaided with #104, not fixed, so re-opening.

**Comment by ryan-roemer** [comment]
Issues #107 overrides this issue and we should come back to it / solve this at the same time.

**Comment by ryan-roemer** [comment]
Reviewing the mechanics of what would have to happen, I think this is really the artifact of needing a completely clean node_modules install and the issue manifested like:

Original: both root and builder use `lodash@3.x`

```
root/
  node_modules/
    lodash@3.x
    builder
```

Then a local, not-from-scratch upgrade left us with:

```
root/
  node_modules/
    lodash@4.x
    builder
      node_modules/
        // NO LODASH HERE
```

whereas a clean install would have done:


```
root/
  node_modules/
    lodash@4.x
    builder
      node_modules/
        lodash@3.x
```

Which would have had builder pick up the correct lodash.

Going to switch this to a `[TRACKING]` issue instead.

**Comment by ryan-roemer** [comment]
New Chalk issue:

```
<project>/node_modules/chalk/index.js:76
	var originalDim = ansiStyles.dim.open;
	                                ^

TypeError: Cannot read property 'open' of undefined
    at Function.applyStyle (<project>/node_modules/chalk/index.js:76:34)
    at Chalk.builder (<project>/node_modules/chalk/index.js:40:21)
    at Object.module.exports._wrapper (<project>/node_modules/builder/lib/log.js:97:37)
    at <project>/node_modules/builder/lib/log.js:67:21
    at Array.forEach (native)
    at Object.module.exports._drainQueue (<project>/node_modules/builder/lib/log.js:66:24)
    at Object.module.exports.setLevel (<project>/node_modules/builder/lib/log.js:54:9)
    at module.exports (<project>/node_modules/builder/bin/builder-core.js:35:7)
    at Object.<anonymous> (/Users/rye/scm/fmd/builder/bin/builder.js:43:1)
    at Module._compile (module.js:435:26)
```

Tree:

```
$ npm ls | grep chalk
│ │ │ │   │ │ ├─┬ chalk@1.1.3
│ │ ├─┬ chalk@0.4.0
│ │   │ ├─┬ chalk@0.4.0
│ │ └─┬ chalk@1.1.1
│   │ ├─┬ chalk@0.4.0
│ │ │ │ ├─┬ chalk@1.1.1
│ │ │   │ │ ├─┬ chalk@0.4.0
│ ├─┬ chalk@1.1.3
│ │ ├─┬ chalk@1.1.1
```

**Comment by ryan-roemer** [comment]
This whole thing is likely https://github.com/npm/npm/issues/10727. Closing unless reoccurrence without "double install" scenario appears.
